"""Shared setup for the figure scripts.

Import this first in every ``generate_figure.py``; it puts ``src/`` on the path so
the scripts run from their own directory without installation.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

import matplotlib as mpl  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))

from COLORMAP import MEDIUM_COLORS as _MEDIUM_BY_CODE  # noqa: E402
from COLORMAP import PHASE_DIAGRAM_COLORS as _PHASE  # noqa: E402

#: Outcome colours, from COLORMAP.py so the whole repository agrees.
OUTCOME_COLORS = {
    "Dominance": _PHASE["Dominance"],
    "Mixture": _PHASE["Mixing"],
    "Restructuring": _PHASE["Restructuring"],
}

#: Medium colours, keyed by the names used in the paper.
MEDIUM_COLORS = {
    "Nutr-": _MEDIUM_BY_CODE["LN"],
    "Base": _MEDIUM_BY_CODE["MN"],
    "Nutr+": _MEDIUM_BY_CODE["HN"],
}

#: Grey used for the parental-label-swapped counterpart points.
SWAPPED_COLOR = "grey"
SWAPPED_ALPHA = 0.2

#: Marker shape by initial species-pool size, as the Fig. 1e and 4c captions
#: specify.
POOL_MARKERS = {6: "o", 12: "s", 24: "^"}

#: Marker alpha deepens with pool size in the published panels.
POOL_ALPHAS = (0.5, 0.7, 0.9)

#: Colour ramp for the simulated density maps, dark to light.
DENSITY_RAMP = ["#802000", "#9a4a30", "#c08674", "#e4c0b6", "#ffebe6"]

#: Outcome classes bottom to top in the stacked fraction panels.
OUTCOME_ORDER = ["Dominance", "Mixture", "Restructuring"]

MM = 0.1 / 2.54  # matplotlib works in inches; the figures are specified in mm


def use_paper_style():
    """Apply the rcParams the published panels were drawn with.

    Values come from ``common_setup.py`` in the working tree, so panels
    generated here match those generated by the Extended Data and
    Supplementary scripts.
    """
    mpl.rcParams.update(
        {
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "font.family": "Arial",
            "figure.dpi": 200,
            "font.size": 8,
            "axes.linewidth": 0.5,
            "xtick.minor.width": 0.4,
            "xtick.major.width": 0.5,
            "ytick.minor.width": 0.4,
            "ytick.major.width": 0.5,
            "text.usetex": False,
            "xtick.direction": "in",
            "ytick.direction": "in",
            "svg.fonttype": "none",  # keep text editable for figure assembly
        }
    )


def draw_similarity_boundaries(ax, limit=1.05):
    """Draw the two-parent similarity map frame, as the published panels have it.

    Four elements, matching Fig. 1e / 4c / 6b:

    * faint grey reference arcs at r = 0.25, 0.5, 0.75, 1.0;
    * a dashed outer arc at r = 1 and a dashed inner arc at the Restructuring
      boundary r = 1/sqrt(2);
    * dashed radial rays at pi/8 and 3pi/8 separating Dominance from Mixture,
      drawn only between the two arcs rather than from the origin;
    * dashed lines along x = 0 and y = 0.

    All spines are hidden -- the arcs are the frame.
    """
    theta = np.linspace(0, np.pi / 2, 300)

    # Faint reference arcs underneath everything.
    for radius in (0.25, 0.5, 0.75, 1.0):
        ax.plot(radius * np.cos(theta), radius * np.sin(theta),
                color="grey", alpha=0.2, linewidth=0.5, zorder=0)

    inner = np.sqrt(0.5)
    dashed = dict(color="black", linewidth=0.8, linestyle=(0, (4, 4)), zorder=3)
    ax.plot(np.cos(theta), np.sin(theta), **dashed)
    ax.plot(inner * np.cos(theta), inner * np.sin(theta), **dashed)

    # Dominance/Mixture boundaries, between the two arcs only.
    for angle in (np.pi / 8, 3 * np.pi / 8):
        ax.plot([inner * np.cos(angle), np.cos(angle)],
                [inner * np.sin(angle), np.sin(angle)], **dashed)

    ax.axhline(0, color="black", linewidth=0.8, linestyle="--", zorder=3)
    ax.axvline(0, color="black", linewidth=0.8, linestyle="--", zorder=3)

    ax.set_xlim(-0.05, limit)
    ax.set_ylim(-0.05, limit)
    ax.set_aspect("equal")
    ax.set_xticks([0, 0.5, 1])
    ax.set_yticks([0, 0.5, 1])
    ax.set_xticklabels(["0.0", "0.5", "1.0"])
    ax.set_yticklabels(["0.0", "0.5", "1.0"])
    for spine in ax.spines.values():
        spine.set_visible(False)


def panel_dir():
    """Output directory for the calling figure, created if needed."""
    caller = Path(sys.argv[0]).resolve().parent
    out = caller / "panels"
    out.mkdir(exist_ok=True)
    return out


def save(fig, name):
    """Write one panel as PDF and report where it went.

    PDF keeps the panel as vector art with editable text (``pdf.fonttype`` is
    42), which is what the figure-assembly step needs.
    """
    path = panel_dir() / f"{name}.pdf"
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {path.relative_to(REPO_ROOT)}")
    return path


def stacked_outcome_bar(ax, table, annotate=None, width=0.6):
    """Draw one stacked outcome bar for a single condition.

    The published fraction panels are a single stacked bar per condition,
    Dominance at the bottom, then Mixture, then Restructuring, at alpha 0.85 --
    not grouped bars. ``annotate`` may be ``"count"`` or ``"percent"`` to label
    each band.
    """
    codes = {"Dominance": 0, "Mixture": 1, "Restructuring": 2}
    total = len(table)
    bottom = 0.0
    for name in OUTCOME_ORDER:
        n = int((table.outcome == codes[name]).sum())
        fraction = n / total if total else 0.0
        ax.bar(0, fraction, bottom=bottom, width=width,
               color=OUTCOME_COLORS[name], alpha=0.85, linewidth=0)
        if annotate and fraction > 0.03:
            if annotate == "count":
                ax.text(0, bottom + fraction / 2, f"$\\it{{{name[0]}}}$\n(n={n})",
                        ha="center", va="center", fontsize=7, linespacing=1.4)
            else:
                ax.text(0, bottom + fraction / 2, f"{fraction:.0%}",
                        ha="center", va="center", fontsize=6)
        bottom += fraction

    ax.set_xlim(-width / 2, width / 2)
    ax.set_ylim(0, 1)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)


def stacked_outcome_series(ax, fractions, separators=True, annotate=True):
    """Stacked step-fill of outcome fractions across conditions.

    This is the ``create_phase_diagram`` idiom from the working tree: a
    step-filled area chart with dashed separators between conditions and the
    percentages written into each band, rather than grouped bars with a legend.
    """
    import numpy as _np

    labels = list(fractions.index)
    n = len(labels)
    x = _np.arange(n + 1)

    bottom = _np.zeros(n + 1)
    for name in OUTCOME_ORDER:
        values = _np.append(fractions[name].to_numpy(dtype=float), 0.0)
        ax.fill_between(x, bottom, bottom + values, step="post",
                        color=OUTCOME_COLORS[name], alpha=0.85, edgecolor="none")
        if annotate:
            for i in range(n):
                if values[i] > 0.04:
                    ax.text(i + 0.5, bottom[i] + values[i] / 2,
                            f"{values[i]:.0%}", ha="center", va="center",
                            fontsize=6)
        bottom = bottom + values

    if separators:
        for boundary in range(1, n):
            ax.axvline(boundary, color="black", linestyle="--",
                       alpha=0.5, linewidth=1)

    ax.set_xlim(0, n)
    ax.set_ylim(0, 1)
    ax.set_xticks([i + 0.5 for i in range(n)])
    ax.set_xticklabels(labels)
    ax.set_yticks([0, 1])
    ax.set_yticklabels(["0", "1"])
    for tick, label in zip(ax.get_xticklabels(), labels):
        if label in MEDIUM_COLORS:
            tick.set_color(MEDIUM_COLORS[label])
            tick.set_style("italic")


def marginal_pdi_histogram(ax, pdi, swapped_pdi, colour, bins=20):
    """Draw the PDI histogram that sits below a similarity map.

    Two overlaid density histograms: the events under the original parental
    labelling in the medium colour, and their label-swapped counterparts in
    grey. Density is on a fixed 0-10 axis so the three media are comparable,
    and the panel carries a full box frame rather than two spines.
    """
    ax.hist(swapped_pdi[np.isfinite(swapped_pdi)], bins=bins, range=(0, 1),
            density=True, color="#808080", alpha=0.85, linewidth=0)
    ax.hist(pdi[np.isfinite(pdi)], bins=bins, range=(0, 1),
            density=True, color=colour, alpha=0.85, linewidth=0)

    ax.set_xlim(0, 1)
    ax.set_ylim(0, 10)
    ax.set_xticks([0, 0.5, 1])
    ax.set_yticks([0, 10])
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_linewidth(0.8)
        spine.set_color("#262626")


def density_map(ax, x1, x2, gridsize=120, bandwidth=0.15):
    """Draw the simulated outcome map as a 2-D density field.

    The published simulation panels show a smoothed density over the
    similarity map rather than individual points, on a white-to-brown ramp.
    Returns the mappable so the caller can attach a colourbar.
    """
    from matplotlib.colors import LinearSegmentedColormap
    from scipy.stats import gaussian_kde

    cmap = LinearSegmentedColormap.from_list(
        "coalescence_density", list(reversed(DENSITY_RAMP))
    )

    # Mirror the sample across the diagonal: the map has no intrinsic parent
    # ordering, and the published field is symmetric about it.
    points = np.vstack([
        np.concatenate([x1, x2]),
        np.concatenate([x2, x1]),
    ])
    kde = gaussian_kde(points, bw_method=bandwidth)

    grid = np.linspace(0, 1.05, gridsize)
    xx, yy = np.meshgrid(grid, grid)
    density = kde(np.vstack([xx.ravel(), yy.ravel()])).reshape(xx.shape)
    density[np.hypot(xx, yy) > 1.0] = np.nan

    return ax.pcolormesh(xx, yy, density, cmap=cmap, shading="auto", zorder=0)
