"""Shared setup for the figure scripts.

Import this first in every ``make_panels.py``; it puts ``src/`` on the path so
the scripts run from their own directory without installation.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

import matplotlib as mpl  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))

from COLORMAP import MEDIUM_COLORS as _MEDIUM_BY_CODE  # noqa: E402
from COLORMAP import PHASE_DIAGRAM_COLORS as _PHASE  # noqa: E402

#: Outcome colours, from COLORMAP.py so the whole repository agrees.
OUTCOME_COLORS = {
    "Dominance": _PHASE["Dominance"],
    "Mixture": _PHASE["Mixing"],
    "Restructuring": _PHASE["Restructuring"],
}

#: Medium colours, keyed by the names used in the paper.
MEDIUM_COLORS = {
    "Nutr-": _MEDIUM_BY_CODE["LN"],
    "Base": _MEDIUM_BY_CODE["MN"],
    "Nutr+": _MEDIUM_BY_CODE["HN"],
}

#: Grey used for the parental-label-swapped counterpart points.
SWAPPED_COLOR = "grey"
SWAPPED_ALPHA = 0.2

MM = 0.1 / 2.54  # matplotlib works in inches; the figures are specified in mm


def use_paper_style():
    """Apply the rcParams the published panels were drawn with.

    Values come from ``common_setup.py`` in the working tree, so panels
    generated here match those generated by the Extended Data and
    Supplementary scripts.
    """
    mpl.rcParams.update(
        {
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "font.family": "Arial",
            "figure.dpi": 200,
            "font.size": 8,
            "axes.linewidth": 0.5,
            "xtick.minor.width": 0.4,
            "xtick.major.width": 0.5,
            "ytick.minor.width": 0.4,
            "ytick.major.width": 0.5,
            "text.usetex": False,
            "xtick.direction": "in",
            "ytick.direction": "in",
            "svg.fonttype": "none",  # keep text editable for figure assembly
        }
    )


def draw_similarity_boundaries(ax, limit=1.02):
    """Draw the two-parent similarity map frame.

    The published maps carry a solid outer arc at r = 1, a dashed inner arc at
    the Restructuring boundary r = 1/sqrt(2), dashed radial rays at pi/8 and
    3pi/8 marking the Dominance/Mixture boundaries, and solid axis lines. All
    four spines are hidden; the arcs are the frame.

    Ported from ``draw_similarity_boundaries`` in the working tree so every
    map panel in the repository is drawn the same way.
    """
    theta = np.linspace(0, np.pi / 2, 300)

    ax.plot(np.cos(theta), np.sin(theta), color="black", linewidth=1.5)

    radius = np.sqrt(0.5)
    ax.plot(radius * np.cos(theta), radius * np.sin(theta),
            color="black", linewidth=0.8, linestyle=(0, (4, 4)))

    for angle in (np.pi / 8, 3 * np.pi / 8):
        ax.plot([0, np.cos(angle)], [0, np.sin(angle)],
                color="black", linewidth=0.8, linestyle=(0, (4, 4)))

    ax.plot([0, 0], [0, 1], color="black", linewidth=1.0)
    ax.plot([0, 1], [0, 0], color="black", linewidth=1.0)

    ax.set_xlim(0, limit)
    ax.set_ylim(0, limit)
    ax.set_aspect("equal")
    ax.set_xticks([0, 0.5, 1])
    ax.set_yticks([0, 0.5, 1])
    ax.tick_params(length=0, pad=1)
    for spine in ax.spines.values():
        spine.set_visible(False)


def panel_dir():
    """Output directory for the calling figure, created if needed."""
    caller = Path(sys.argv[0]).resolve().parent
    out = caller / "panels"
    out.mkdir(exist_ok=True)
    return out


def save(fig, name):
    """Write one panel as PDF and report where it went.

    PDF keeps the panel as vector art with editable text (``pdf.fonttype`` is
    42), which is what the figure-assembly step needs.
    """
    path = panel_dir() / f"{name}.pdf"
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {path.relative_to(REPO_ROOT)}")
    return path
